type User {
    id: ID! @rename(attribute: "public_id")
    email: String!
    phone: String
    admins: [Admin!]! @hasMany
    lecturers: [Lecturer!]! @hasMany
    students: [Student!]! @hasMany
    schools: [School!]! @hasMany(relation: "schools")
    applicants: [Applicant!]! @hasMany(relation: "applicants")

    account: Account @morphOne
    assignedReceiptBooks: [ReceiptBook!]! @hasMany(relation: "assignedReceiptBooks")
    processedTransactions: [Transaction!]! @hasMany(relation: "processedTransactions")

    createdAt: DateTime! @rename(attribute: "created_at")
    updatedAt: DateTime! @rename(attribute: "updated_at")
}
